services:
  db:
    image: postgres:13
    container_name: messenger-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - messenger-network

  web:
    build: .
    container_name: messenger-web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - messenger-network

  alembic:
    build:
      context: .
    container_name: messenger-alembic
    command: alembic upgrade head
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - messenger-network

  test:
    build:
      context: .
    container_name: messenger-test
    command: pytest --cov=app --cov-report=term-missing
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
    networks:
      - messenger-network

volumes:
  postgres_data:

networks:
  messenger-network:
    driver: bridge
